apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: kafka-external
      protocol: TCP
      port: 9092
      targetPort: 9092
  selector:
    app: redpanda